// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBHrd4DTZUQcpVpgZpK6nXVhM5PHVVm2GA',
    appId: '1:556322918014:web:5351b39496255ea2fb122f',
    messagingSenderId: '556322918014',
    projectId: 'dsal-5fd73',
    authDomain: 'dsal-5fd73.firebaseapp.com',
    storageBucket: 'dsal-5fd73.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_yNJzl9MX3n9CnK_p4PUCTTiD2XutMNQ',
    appId: '1:556322918014:android:e041942a28483723fb122f',
    messagingSenderId: '556322918014',
    projectId: 'dsal-5fd73',
    storageBucket: 'dsal-5fd73.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBTXVVhvX6iQXsfyPzJMRZaollHowIqEoU',
    appId: '1:556322918014:ios:390a998fae50a94efb122f',
    messagingSenderId: '556322918014',
    projectId: 'dsal-5fd73',
    storageBucket: 'dsal-5fd73.firebasestorage.app',
    iosBundleId: 'com.example.dsal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBTXVVhvX6iQXsfyPzJMRZaollHowIqEoU',
    appId: '1:556322918014:ios:390a998fae50a94efb122f',
    messagingSenderId: '556322918014',
    projectId: 'dsal-5fd73',
    storageBucket: 'dsal-5fd73.firebasestorage.app',
    iosBundleId: 'com.example.dsal',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBHrd4DTZUQcpVpgZpK6nXVhM5PHVVm2GA',
    appId: '1:556322918014:web:bf45895bd37ead71fb122f',
    messagingSenderId: '556322918014',
    projectId: 'dsal-5fd73',
    authDomain: 'dsal-5fd73.firebaseapp.com',
    storageBucket: 'dsal-5fd73.firebasestorage.app',
  );
}
